In [1]:
import numpy as np
B = np.arange(3)
print (B)
#print np.exp(B)
print (np.sqrt(B))

[0 1 2]
[ 0.          1.          1.41421356]


In [5]:
#Return the floor of the input
a = np.floor(10*np.random.random((3,4)))
print (a)

print(a.shape)
## flatten the array
print (a.ravel())
a.shape = (6, 2)
print (a) 
print (a.T)
print (a.resize((2,6)))
print (a)

#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
a.reshape(3,-1)

[[ 0.  8.  4.  7.]
 [ 4.  3.  2.  5.]
 [ 1.  9.  2.  5.]]
(3, 4)
[ 0.  8.  4.  7.  4.  3.  2.  5.  1.  9.  2.  5.]
[[ 0.  8.]
 [ 4.  7.]
 [ 4.  3.]
 [ 2.  5.]
 [ 1.  9.]
 [ 2.  5.]]
[[ 0.  4.  4.  2.  1.  2.]
 [ 8.  7.  3.  5.  9.  5.]]
None
[[ 0.  8.  4.  7.  4.  3.]
 [ 2.  5.  1.  9.  2.  5.]]


array([[ 0.,  8.,  4.,  7.],
       [ 4.,  3.,  2.,  5.],
       [ 1.,  9.,  2.,  5.]])

In [6]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print (a)
print ('---')
print (b)
print ('---')
print (np.hstack((a,b)))
#np.hstack((a,b))

[[ 8.  5.]
 [ 8.  4.]]
---
[[ 8.  4.]
 [ 8.  7.]]
---
[[ 8.  5.  8.  4.]
 [ 8.  4.  8.  7.]]


In [9]:
a = np.floor(10*np.random.random((2,12)))
print (a)
print (np.hsplit(a,3))
print (np.hsplit(a,(3,9)))   # Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print (a)
np.vsplit(a,3)

[[ 2.  6.  7.  4.  8.  8.  6.  1.  7.  3.  9.  1.]
 [ 5.  8.  5.  3.  5.  1.  2.  9.  5.  1.  9.  3.]]
[array([[ 2.,  6.,  7.,  4.],
       [ 5.,  8.,  5.,  3.]]), array([[ 8.,  8.,  6.,  1.],
       [ 5.,  1.,  2.,  9.]]), array([[ 7.,  3.,  9.,  1.],
       [ 5.,  1.,  9.,  3.]])]
[array([[ 2.,  6.,  7.],
       [ 5.,  8.,  5.]]), array([[ 4.,  8.,  8.,  6.,  1.,  7.],
       [ 3.,  5.,  1.,  2.,  9.,  5.]]), array([[ 3.,  9.,  1.],
       [ 1.,  9.,  3.]])]
[[ 3.  1.]
 [ 8.  4.]
 [ 4.  1.]
 [ 5.  2.]
 [ 2.  1.]
 [ 7.  7.]
 [ 8.  1.]
 [ 3.  1.]
 [ 0.  3.]
 [ 4.  1.]
 [ 9.  2.]
 [ 7.  7.]]


[array([[ 3.,  1.],
        [ 8.,  4.],
        [ 4.,  1.],
        [ 5.,  2.]]), array([[ 2.,  1.],
        [ 7.,  7.],
        [ 8.,  1.],
        [ 3.,  1.]]), array([[ 0.,  3.],
        [ 4.,  1.],
        [ 9.,  2.],
        [ 7.,  7.]])]

In [10]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
print(b is a)
b.shape = 3,4
print (a.shape)
print (id(a))
print (id(b))

True
(3, 4)
92134016
92134016


In [11]:
#The view method creates a new array object that looks at the same data.
c = a.view()
print(c is a)
c.shape = 2,6
#print a.shape
c[0,4] = 1234
a

False


array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [46]:
#The copy method makes a complete copy of the array and its data.
d = a.copy() 
d is a
d[0,0] = 9999
print d 
print a

[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
