In [4]:
import numpy as np
#1:8*8棋盘矩阵，其中1、3、5、7行&&0、2、4、6列的元素置为1   1 ,3，5，7列&&0,2,4,6行也是1
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
#z[::2,1::2] = 1
print (z)


[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [6]:
#2：min()、max()函数

In [5]:
z = np.random.random((10,10))
zmin,zmax = z.min(),z.max()

In [11]:
#归一化，将矩阵规格化到0～1，即最小的变成0，最大的变成1，最小与最大之间的等比缩放
z = 10*np.random.random((5,5))
print (z,'\n')
zmin,zmax = z.min(axis=1),z.max(axis=1)
z = (z-zmin)/(zmax-zmin)
print (z)

[[ 7.58614129  5.89420562  5.66362352  6.03883598  2.46880656]
 [ 9.46825444  0.4158072   9.02688275  1.1464188   7.55163902]
 [ 5.97594772  8.23389774  0.69467222  6.31678802  7.44306729]
 [ 9.20419986  6.79309779  9.44632469  9.42846594  5.05001035]
 [ 3.21944733  7.33767695  3.35764522  1.59004158  0.1250408 ]] 

[[ 1.          0.60518424  0.65907981  0.2249215   0.32495272]
 [ 1.36779168  0.          1.10518123 -0.88792367  1.02966489]
 [ 0.68534527  0.86364387  0.          0.28814538  1.0146119 ]
 [ 1.31619166  0.70448249  1.16081585  0.99593779  0.68282518]
 [ 0.14668588  0.76464072  0.35321572 -0.78701578  0.        ]]


In [12]:
#矩阵相加
z = np.zeros((5,5))
z += np.arange(5)
print (np.arange(5))
print (z)


[0 1 2 3 4]
[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [18]:
#生成0~10之间均匀分布的11个数，包括0和10

z = np.linspace(0,10,11)
print (z)
m = np.logspace(1,4,4,base=2)
m

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


array([  2.,   4.,   8.,  16.])

In [18]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [20]:
import numpy as np
a = np.array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55],
       [ 1,  2,  3,  4,  5,  6]])


In [21]:
a[2:5:2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [22]:
b=[3,5]
a[b,::2]

array([[30, 32, 34],
       [50, 52, 54]])