In [2]:
import tensorflow as tf
import numpy as np

In [12]:
#第一个tensorflow例子,创建一个计算图
a = tf.Variable(np.random.random([2,2]))
b = tf.Variable(np.random.random([2,2]))
res = tf.matmul(a,b)
init_op = tf.global_variables_initializer()

In [30]:
#Tensorflow中的所有操作，都需要在Session中执行
with tf.Session() as sess:
    #调用session上的run方法运行图
    sess.run(init_op)
    print(a.eval())
    print(b.eval())
    print('-----------------------------')
    print(res.eval())
    print(sess.run(res))

[[ 0.77693286  0.30337097]
 [ 0.20540581  0.46197954]]
[[ 0.30389118  0.19378293]
 [ 0.86185497  0.92127162]]
-----------------------------
[[ 0.49756482  0.43004339]
 [ 0.46058038  0.46541278]]
[[ 0.49756482  0.43004339]
 [ 0.46058038  0.46541278]]


### 基本操作

##### tensorflow里面的操作算子跟numpy里面的很多算子是类似的

In [53]:
#### 1.定义元素为0的tensor
a = tf.zeros([2,3])
b = tf.Variable(np.random.random([4,5]))
aa = tf.zeros_like(b)
c = tf.ones([3,7])
cc = tf.ones_like(b)
#定义常量
d = tf.constant(np.random.random([3,6]))
#linspace
e = tf.linspace(1.0,5.0,5,name='linspace')
#range序列
f = tf.range(10,20,2)
#生成随机tensor变量
g = tf.random_normal([2,6])
#洗牌操作
h = tf.random_shuffle(g)
with tf.Session() as sess:
    print('zeros:\n%s'%(sess.run(a)))
    print('zeros_like:\n%s'%(sess.run(aa)))
    print('ones:\n%s'%(sess.run(c)))
    print('ones_like:\n%s'%(sess.run(cc)))
    print('constant:\n%s'%(sess.run(d)))
    print('linspace:\n%s'%(sess.run(e)))
    print('range:\n%s'%(sess.run(f)))
    print('random_normal:\n%s'%(sess.run(g)))
    print('random_shuffle:\n%s'%(sess.run(h)))

zeros:
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
zeros_like:
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
ones:
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]
ones_like:
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
constant:
[[ 0.31660333  0.93274365  0.88576333  0.21276277  0.60063155  0.74706908]
 [ 0.81785227  0.00837294  0.52901356  0.79063927  0.67519436  0.08165647]
 [ 0.48268766  0.7035593   0.9296307   0.23192016  0.89041657  0.37935023]]
linspace:
[ 1.  2.  3.  4.  5.]
range:
[10 12 14 16 18]
random_normal:
[[ 0.4583672  -0.62816924 -0.01578521 -0.96882486  0.97768754  1.77148509]
 [-1.17991543 -0.56594795 -1.33655834  1.12693012 -0.06740503  0.90800941]]
random_shuffle:
[[-1.48549628  1.86747241 -0.51968598  1.42260683  0.10085818  0.6981619 ]
 [ 0.46687928  1.58161557  0.34181243 -1.12870979  0.57411706 -1.147367  ]]


### tensorflow中做累加操作

In [64]:
#使用tensorflow做累加
init = tf.Variable(0)
new_value = tf.add(init,tf.constant(1))
#更新，把第二个参数指定的值赋值给第一个参数
update = tf.assign(init,new_value)
#在Session里面完成所有的计算
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(new_value)
    for _ in np.arange(0,10):
        print(sess.run(update))

1
2
3
4
5
6
7
8
9
10


### numpy数据格式转换为tensor数据格式

In [65]:
a = np.random.random([5,6])
b = tf.convert_to_tensor(a)
with tf.Session() as sess:
    print(sess.run(b))

[[ 0.17958437  0.65612458  0.96211077  0.32094504  0.99788719  0.44490107]
 [ 0.92814125  0.68682988  0.36403594  0.86896883  0.52834255  0.26489186]
 [ 0.852673    0.94986708  0.76352973  0.34439875  0.71958958  0.35908035]
 [ 0.44044319  0.07143515  0.64661832  0.23750976  0.78909106  0.31788175]
 [ 0.93294889  0.5094474   0.11082057  0.75866291  0.70132457  0.00739416]]


### 计算图中的占位符

In [70]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = tf.add(a,b)
#先构建出计算图，在Session计算的时候再填入真实的数据
with tf.Session() as sess:
    print(sess.run(c,feed_dict={a:np.random.random(4),b:np.random.random(4)}))

[ 0.78985882  0.61303282  0.98176062  1.34278333]
