In [1]:
import tensorflow as tf

v1 = tf.Variable(tf.random_normal([2,4]), name="v1")
v2 = tf.Variable(tf.random_normal([3,5]), name="v2")
init_op = tf.global_variables_initializer()
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(init_op)
    print ("V1:",sess.run(v1))  
    print ("V2:",sess.run(v2))
    saver_path = saver.save(sess, "./model/model.ckpt")
    print ("模型保存在: ", saver_path) 

V1: [[-0.48337707 -1.38035023 -0.95308626  0.94919461]
 [-1.38756776  1.34212625 -0.27619359  0.417579  ]]
V2: [[-0.17616035 -0.10801019  1.65568447 -0.55630022  0.18890123]
 [ 1.18153358  1.07211208  0.19738743 -2.03522134  1.17540669]
 [ 1.72167706  0.06605922 -0.16109166 -0.7220574   0.48254135]]
Model saved in file:  ./model/model.ckpt


In [2]:
import tensorflow as tf
saver = tf.train.Saver()
with tf.Session() as sess:
    saver.restore(sess, "./model/model.ckpt")
    print ("V1:",sess.run(v1))  
    print ("V2:",sess.run(v2))
    print ("Model restored")

INFO:tensorflow:Restoring parameters from ./model/model.ckpt
V1: [[-0.48337707 -1.38035023 -0.95308626  0.94919461]
 [-1.38756776  1.34212625 -0.27619359  0.417579  ]]
V2: [[-0.17616035 -0.10801019  1.65568447 -0.55630022  0.18890123]
 [ 1.18153358  1.07211208  0.19738743 -2.03522134  1.17540669]
 [ 1.72167706  0.06605922 -0.16109166 -0.7220574   0.48254135]]
Model restored
